name: "Linter: Js"

on:
  pull_request:
    paths:
      - '**.js'

env:
  fail-fast: true

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: |
          npm install
          npm run lint