name: PHPUnit

on:
  push:
  pull_request:

env:
  fail-fast: true

jobs:
  phpunit:
    name: "phpunit - php ${{ matrix.php-version }}"
    runs-on: ubuntu-20.04
    continue-on-error: false

    strategy:
      matrix:
        php-version: ['7.4', '8.0']

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Install PHP with extensions'
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
          ini-values: date.timezone=UTC

      - name: 'Install project dependencies'
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
          vendor/bin/simple-phpunit install

      - name: 'Run tests'
        run: vendor/bin/simple-phpunit -v